### ISSUE TITLE
Scrum 專案標準流程

### ISSUE THREAD

**Issue by 40123112** [40123112/2015cdb_g11#1]
深入了解 Scrum 
1. 專案宗旨
2. 進行流程
3. 摘取重點記錄至本組wordpress
http://cd-cadp.rhcloud.com/get_page?heading=%E5%B0%88%E6%A1%88%E7%AE%A1%E7%90%86

https://copy.com/TcfAzMN6iMGhenDq

**Comment by 2014cdag2** [comment]
今日看了老師給的文章: http://www.delightpress.com.tw/bookRead/skna00001_read.pdf
了解到專案宗旨及進行流程
日後將重點紀錄至本組wordpress

**Comment by 2014cdag2** [comment]
Scrum
●角色
教練SM
產品負責人PO 
開發團隊Developer
●會議
1.衝刺規劃會議（Sprint planning meeting）:完成產品開發需求分成若干個項目即完成項目所需要的時間。
2.每日站立會議（Daily Scrum）：站個開會，並分享昨天做的事情，今日準備做的事情及遇到的困難。
3.衝刺（Sprint）:2~4週的開發活動。
4.衝刺檢視會議（Sprint reivew meeting）: 展示團隊在此2~4週中所完成的每一個需求項目，並且讓產品負責人確認這些項目有做到他心目中所想要的程度。
5.自省會議（Sprint retrospective meeting）：檢討與改善，討論出改善行動方案，在下一個sprint中實施此改善項目。
6.產品清單精進會議（Product backlog refinement meeting）: 產品負責人與開發團隊在每個sprint抽出時間來檢視產品開發裡的需求，然後挑選一些下一個sprint準備要施工的項目。
●產出物:遠景（Vision）及故事（Story）
1.產品清單（Product backlog）：關於此專案或是產品的story 就稱為產品清單，需經過排序，較重要的先開始進行。
2.衝刺清單（Sprint backlog）：可以想成是產品清單的子集合。
3.工作（Task）: 工作是完成story 的施工項目。將每一個story 再細分為若干個task。

而我們現在進行的就是SCRUM，我現在在做的事情就是SPRINT中的某一個STORY。

**Comment by 40123148** [comment]
https://www.dropbox.com/s/vm3rljfhmg2op28/P_20150330_152036.jpg?dl=0

https://www.dropbox.com/s/7j6wnllkiirdhpe/P_20150330_152104.jpg?dl=0

https://www.dropbox.com/s/mkl5s035z3h7ugg/P_20150330_152118.jpg?dl=0
2015/3/30 下午4:10 於 "2014cdag2" <notifications@github.com> 寫道：
