### ISSUE TITLE
2D 漸開線繪製

### ISSUE THREAD

**Issue by 40123112** [40123112/2015cdb_g11#4]
研究如何繪製 2D 漸開線

http://cd-cadp.rhcloud.com/get_page?heading=%E8%AA%B2%E7%A8%8B%E9%80%B2%E5%BA%A6

**Comment by 40123112** [comment]
Solidwork繪製漸開線
http://wenku.baidu.com/view/b27bb47927284b73f2425052.html   
http://coccad.com/subject/about/2329.html

齒輪技術pdf
http://www.khkgears.co.jp/tw/gear_technology/pdf/gear_guide1.pdf

**Comment by 40123112** [comment]
http://cmsimply.cycu.org/brython?filename=yen_spur_gear_contour.py
這篇是由Canvas (HTML元素)所寫成的2D齒輪動態渲染點陣圖像

http://cd-cadp.rhcloud.com/get_page?heading=2D+%E6%AD%A3%E9%BD%92%E8%BC%AA%E8%BC%AA%E5%BB%93
這篇則是由Python內建的Tkinter所寫成的2D 正齒輪輪廓

閱讀並了解這篇兩篇的齒輪畫法，發現這兩篇的程式大致上是一模一樣的。

**Comment by 40123148** [comment]
請問什麼是Canvas、Tkinter、動態渲染點陣圖像?
